### ISSUE TITLE
V2 only support

### ISSUE THREAD

**Issue by zbal** [Wiredcraft/dopy#36]
DigitalOcean deprecated API v1, a lot of the code was V1 specific and is now not required and is dead code. 

Revamp the code to make it v2 only.

**Comment by sunsongxp** [comment]
DO API V2 only support coding is finished. Writing tests.

**Comment by sunsongxp** [comment]
The tool I am using for testing dopy is responses https://github.com/getsentry/responses. This is a project mocking requests (python package). To test this project, the idea is to test the requests and response content of each api communication, instead of communicate through real api, the responses test tool imitate that process, then make sure in each test, the request/response content are valid to pass tests.

**Comment by sunsongxp** [comment]
Code refactoring is basically finished, tests covers 50% of dopy/manager.py. Needs to make sure it's compatible to the version before refactoring.

**Comment by sunsongxp** [comment]
Still writing tests, it is now 71% of dopy/manage.py.
